### ISSUE TITLE
独显的配置

### ISSUE THREAD

**Issue by BDZNH** [gregrgr/TUF_B360M_GAMING_PLUS_S_9600K#1]
你好，请问一下，你对独显`RX 560D`有做过哪些单独的配置吗

**Comment by gregrgr** [comment]
独显不需要设置，BIOS里的集显要打开

**Comment by BDZNH** [comment]
@gregrgr 那就很奇怪了。我的是 `RX 5700`，在 Clover 也是不用任何配置就能驱动的，BIOS中集显也是打开的。按理来说应该可以照搬的。

方便问一下你的BIOS都改了哪些吗？就是黑果小兵博客里面的那些内容吗？你的BIOS是哪个版本😐

**Comment by gregrgr** [comment]
英文 | 中文
-- | --
Fast Boot | 快速启动
CFG Lock (MSR 0xE2 write protection) | CFG 锁 (MSR 0xE2 写入保护)
VT-d | VT-d
CSM | 兼容性支持模块

**Comment by gregrgr** [comment]
禁用

英文 | 中文
-- | --
Fast Boot | 快速启动
CFG Lock (MSR 0xE2 write protection) | CFG 锁 (MSR 0xE2 写入保护)
VT-d | VT-d
CSM | 兼容性支持模块

打开

英文 | 中文
-- | --
VT-x | VT-x
Above 4G decoding | 大于 4G 地址空间解码
Hyper Threading | 处理器超线程
Execute Disable Bit | 执行禁止位
EHCI/XHCI Hand-off | 接手 EHCI/XHCI 控制
OS type: other types | 操作系统类型: 其他

**Comment by gregrgr** [comment]
这是opencore，纯UEFI引导的

**Comment by BDZNH** [comment]
@gregrgr 在我这里，VT-x，Hyper Threading，Execute Disable Bit都是没有的。你的主板上能找到这几个选项吗？

方便问一下集显那里的每一条设置信息吗，primary graphics, intel multimonitor，和别的信息。

我的配置和你相比除了硬盘（一般没太大影响），显卡（免驱），网卡（免驱）之外，主板和CPU都是一样的。

**Comment by gregrgr** [comment]
Advanced —> Onboard Devices Configuration-Serial Port Configuration Serial Port —> Off
Advanced —> USB Configuration-XHCI Hand-off —> Enabled
Secure Boot -> OS Type -> Other OS
Advanced —> PCH configuration-IOAPIC 24-119 Entries —> disabled
CFG-LOCK -> disabled
Advanced -> Advanced PCH Configuration -> system time and alarm source -> Legacy RTC

**Comment by BDZNH** [comment]
谢谢你了，还是不行。启动的时候有logo显示，logo过去之后就黑了。但是看电脑已经连上了WiFi，也能ping通。很奇怪。

**Comment by BDZNH** [comment]
我想办法弄吧

**Comment by BDZNH** [comment]
@gregrgr 加了一个启动参数就好了　
```
agdpmod=pikera
```

**Comment by BDZNH** [comment]
核显频率太低了，4K高码率的视频播起来很卡。可以试一下打缓冲帧补丁，加魔改 watevergreen
